name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-dotcom-n2y
      SKIP_NODE: false
      SKIP_GO: false
      SKIP_SBT: true
      GO_VERSION_FILE: api/go.mod
      NODE_VERSION_FILE: ui/.nvmrc
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
